# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [3]:
#Creating sample array
arr = np.arange(50,61)

In [4]:
#Show
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

##### picking single values

In [5]:
#Get a value at an index
arr[0]

50

In [6]:
#Get a value at an index
arr[-1]

60

##### pick a slice of data

In [8]:
#Get values in a range
arr[1: -2]

array([51, 52, 53, 54, 55, 56, 57, 58])

In [6]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

##### picking specific values

In [15]:
arr[[0, 2, 8]]

array([50, 52, 58])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [16]:
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [18]:
#Setting a value with index range (Broadcasting)
arr[-5:] = 100

#Show
arr

array([ 50,  51,  52,  53,  54,  55, 100, 100, 100, 100, 100])

In [20]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(50,61)

#Show
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [21]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([50, 51, 52, 53, 54, 55])

In [22]:
# Change Slice
slice_of_arr[:] = 99

# Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [24]:
arr

array([99, 99, 99, 99, 99, 99, 56, 57, 58, 59, 60])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [25]:
#To get a copy, need to be explicit
slice_of_arr = arr[-5:].copy()

slice_of_arr

array([56, 57, 58, 59, 60])

In [27]:
slice_of_arr[:] = 8

In [28]:
slice_of_arr

array([8, 8, 8, 8, 8])

In [29]:
arr

array([99, 99, 99, 99, 99, 99, 56, 57, 58, 59, 60])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [43]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [47]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [15]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [53]:
# Getting individual element value
arr_2d[1, 0]

20

In [49]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

##### picking single values

In [54]:
arr_2d[-1 , -1]

45

##### picking slices

In [58]:
arr_2d[0 , -2:]

array([10, 15])

##### picking specific items

In [60]:
arr_2d[0 , [0, -1] ]

array([ 5, 15])

##### some more examples

In [17]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [18]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [19]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [63]:
#Set up matrix
arr2d = np.zeros((10,10))

In [64]:
#Length of array
arr_length = arr2d.shape[1]

In [65]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [71]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [72]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to fins useful images, like this one:

<img src= 
'http://memory.osu.edu/classes/python/_images/numpy_indexing.png' width=500/>

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [77]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [81]:
bool_arr = arr>4

In [82]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

##### indexing using conditions

In [87]:
arr<4

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [88]:
arr[arr<4]

array([1, 2, 3])

In [93]:
arr[(arr<=8) & (arr >=4)]

array([4, 5, 6, 7, 8])

In [94]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])